// i18n.ts
// -----------------------------------------------------------------------------
// WHAT: All UI text in both English and Hindi, in one place.
// WHY:  The app is bilingual. Centralizing strings here means (a) translators or
//       future devs change copy in ONE file, and (b) the rendering components
//       stay clean — they call `t(lang).heroTitle` instead of hard-coding text.
//       NOTE: This covers the *app shell* (buttons, labels). The *report content*
//       itself is generated by the AI directly in the chosen language.
// -----------------------------------------------------------------------------

import type { Language } from '../types';

/** The shape every language pack must satisfy (TypeScript enforces parity). */
export interface Strings {
  appName: string;
  tagline: string;
  heroTitle: string;
  heroSubtitle: string;
  chooseLanguage: string;
  english: string;
  hindi: string;
  uploadCta: string;
  uploadHint: string;
  uploadDrop: string;
  fileTooLarge: string;
  wrongFileType: string;
  selectedFile: string;
  removeFile: string;
  generate: string;
  analyzing: string;
  analyzingHint: string;
  // Result screen
  yourReport: string;
  overallSummary: string;
  importantFindings: string;
  allParameters: string;
  foodRecommendations: string;
  foodsToLimit: string;
  lifestyle: string;
  questionsForDoctor: string;
  whenToSeeDoctor: string;
  disclaimer: string;
  downloadPdf: string;
  startOver: string;
  parameter: string;
  value: string;
  range: string;
  status: string;
  statusNormal: string;
  statusHigh: string;
  statusLow: string;
  statusWatch: string;
  bannerGood: string;
  bannerAttention: string;
  bannerSeeDoctor: string;
  // Errors
  genericError: string;
  preparingPdf: string;
  footerDisclaimer: string;
}

const en: Strings = {
  appName: 'HealthDecode',
  tagline: 'Understand your medical report in plain language.',
  heroTitle: 'Understand your lab report in a minute',
  heroSubtitle:
    'Upload your medical report PDF and get a clear, friendly explanation of what every value means — and what to do next.',
  chooseLanguage: 'Choose your report language',
  english: 'English',
  hindi: 'हिन्दी',
  uploadCta: 'Upload report PDF',
  uploadHint: 'PDF up to 15 MB. Scanned reports are supported.',
  uploadDrop: 'Drop your PDF here or tap to browse',
  fileTooLarge: 'That file is larger than 15 MB. Please upload a smaller PDF.',
  wrongFileType: 'Please upload a PDF file.',
  selectedFile: 'Selected file',
  removeFile: 'Remove',
  generate: 'Generate my report',
  analyzing: 'Reading your report…',
  analyzingHint: 'Our AI is extracting and explaining every value. This takes a few seconds.',
  yourReport: 'Your Health Report',
  overallSummary: 'Overall Summary',
  importantFindings: 'Important Findings',
  allParameters: 'Every Parameter Explained',
  foodRecommendations: 'Foods That Help',
  foodsToLimit: 'Foods to Limit',
  lifestyle: 'Lifestyle Suggestions',
  questionsForDoctor: 'Questions to Ask Your Doctor',
  whenToSeeDoctor: 'When to See a Doctor',
  disclaimer: 'Important Disclaimer',
  downloadPdf: 'Download PDF',
  startOver: 'Analyze another report',
  parameter: 'Parameter',
  value: 'Value',
  range: 'Normal Range',
  status: 'Status',
  statusNormal: 'Normal',
  statusHigh: 'High',
  statusLow: 'Low',
  statusWatch: 'Watch',
  bannerGood: 'Most of your values look normal. Keep up the healthy habits!',
  bannerAttention: 'A few values need attention. Lifestyle changes can help — see below.',
  bannerSeeDoctor: 'Some values need a doctor’s review. Please consult a healthcare professional.',
  genericError:
    'Sorry, we could not read this report. Please make sure it is a clear medical lab report PDF and try again.',
  preparingPdf: 'Preparing your PDF…',
  footerDisclaimer:
    'HealthDecode provides general information only and is not a medical diagnosis. Always consult a qualified doctor.',
};

const hi: Strings = {
  appName: 'HealthDecode',
  tagline: 'अपनी मेडिकल रिपोर्ट को आसान भाषा में समझें।',
  heroTitle: 'अपनी लैब रिपोर्ट को एक मिनट में समझें',
  heroSubtitle:
    'अपनी मेडिकल रिपोर्ट की PDF अपलोड करें और हर वैल्यू का आसान, सरल अर्थ जानें — और आगे क्या करना है यह भी।',
  chooseLanguage: 'अपनी रिपोर्ट की भाषा चुनें',
  english: 'English',
  hindi: 'हिन्दी',
  uploadCta: 'रिपोर्ट PDF अपलोड करें',
  uploadHint: '15 MB तक की PDF। स्कैन की गई रिपोर्ट भी चलेगी।',
  uploadDrop: 'अपनी PDF यहाँ डालें या चुनने के लिए टैप करें',
  fileTooLarge: 'यह फ़ाइल 15 MB से बड़ी है। कृपया छोटी PDF अपलोड करें।',
  wrongFileType: 'कृपया PDF फ़ाइल अपलोड करें।',
  selectedFile: 'चुनी गई फ़ाइल',
  removeFile: 'हटाएँ',
  generate: 'मेरी रिपोर्ट बनाएँ',
  analyzing: 'आपकी रिपोर्ट पढ़ी जा रही है…',
  analyzingHint: 'हमारा AI हर वैल्यू निकालकर समझा रहा है। इसमें कुछ सेकंड लगते हैं।',
  yourReport: 'आपकी हेल्थ रिपोर्ट',
  overallSummary: 'समग्र सारांश',
  importantFindings: 'मुख्य निष्कर्ष',
  allParameters: 'हर पैरामीटर की व्याख्या',
  foodRecommendations: 'फ़ायदेमंद आहार',
  foodsToLimit: 'इन्हें कम करें',
  lifestyle: 'जीवनशैली सुझाव',
  questionsForDoctor: 'डॉक्टर से पूछने के सवाल',
  whenToSeeDoctor: 'डॉक्टर को कब दिखाएँ',
  disclaimer: 'महत्वपूर्ण सूचना',
  downloadPdf: 'PDF डाउनलोड करें',
  startOver: 'दूसरी रिपोर्ट जाँचें',
  parameter: 'पैरामीटर',
  value: 'वैल्यू',
  range: 'सामान्य सीमा',
  status: 'स्थिति',
  statusNormal: 'सामान्य',
  statusHigh: 'अधिक',
  statusLow: 'कम',
  statusWatch: 'ध्यान दें',
  bannerGood: 'आपकी ज़्यादातर वैल्यू सामान्य हैं। स्वस्थ आदतें जारी रखें!',
  bannerAttention: 'कुछ वैल्यू पर ध्यान देने की ज़रूरत है। जीवनशैली में बदलाव मदद कर सकते हैं — नीचे देखें।',
  bannerSeeDoctor: 'कुछ वैल्यू के लिए डॉक्टर की सलाह ज़रूरी है। कृपया किसी स्वास्थ्य विशेषज्ञ से मिलें।',
  genericError:
    'क्षमा करें, हम यह रिपोर्ट नहीं पढ़ पाए। कृपया सुनिश्चित करें कि यह एक स्पष्ट मेडिकल लैब रिपोर्ट PDF है और फिर से कोशिश करें।',
  preparingPdf: 'आपकी PDF तैयार की जा रही है…',
  footerDisclaimer:
    'HealthDecode केवल सामान्य जानकारी देता है और यह कोई मेडिकल निदान नहीं है। हमेशा योग्य डॉक्टर से सलाह लें।',
};

const packs: Record<Language, Strings> = { en, hi };

/** Get the string pack for a language. Usage: `const s = t(lang); s.generate`. */
export function t(lang: Language): Strings {
  return packs[lang];
}
